run:
    gradle run --warning-mode all

test:
    gradle test --warning-mode all

tree:
    tree -a

clean-all:
    trash --force "./.gradle/" "./build/" "./.project" "./app/bin/" "./app/build/" "./app/.classpath" "./app/.project" "./app/build/"